<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131103161154 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("CREATE TABLE famelo_satisfy_domain_model_campaign_contacts_join (satisfy_campaign VARCHAR(40) NOT NULL, satisfy_contact VARCHAR(40) NOT NULL, INDEX IDX_F52EADF7AD40DC63 (satisfy_campaign), INDEX IDX_F52EADF7A4A77081 (satisfy_contact), PRIMARY KEY(satisfy_campaign, satisfy_contact))");
		$this->addSql("CREATE TABLE famelo_satisfy_domain_model_campaign_customer_join (satisfy_campaign VARCHAR(40) NOT NULL, satisfy_customer VARCHAR(40) NOT NULL, INDEX IDX_A1DEACD9AD40DC63 (satisfy_campaign), INDEX IDX_A1DEACD9336C40B7 (satisfy_customer), PRIMARY KEY(satisfy_campaign, satisfy_customer))");
		$this->addSql("ALTER TABLE famelo_satisfy_domain_model_campaign_contacts_join ADD CONSTRAINT FK_F52EADF7AD40DC63 FOREIGN KEY (satisfy_campaign) REFERENCES famelo_satisfy_domain_model_campaign (persistence_object_identifier)");
		$this->addSql("ALTER TABLE famelo_satisfy_domain_model_campaign_contacts_join ADD CONSTRAINT FK_F52EADF7A4A77081 FOREIGN KEY (satisfy_contact) REFERENCES famelo_satisfy_domain_model_contact (persistence_object_identifier)");
		$this->addSql("ALTER TABLE famelo_satisfy_domain_model_campaign_customer_join ADD CONSTRAINT FK_A1DEACD9AD40DC63 FOREIGN KEY (satisfy_campaign) REFERENCES famelo_satisfy_domain_model_campaign (persistence_object_identifier)");
		$this->addSql("ALTER TABLE famelo_satisfy_domain_model_campaign_customer_join ADD CONSTRAINT FK_A1DEACD9336C40B7 FOREIGN KEY (satisfy_customer) REFERENCES famelo_satisfy_domain_model_customer (persistence_object_identifier)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("DROP TABLE famelo_satisfy_domain_model_campaign_contacts_join");
		$this->addSql("DROP TABLE famelo_satisfy_domain_model_campaign_customer_join");
	}
}

?>