<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131103232709 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("CREATE TABLE famelo_satisfy_domain_model_campaign_customers_join (satisfy_campaign VARCHAR(40) NOT NULL, satisfy_customer VARCHAR(40) NOT NULL, INDEX IDX_E21BFFF2AD40DC63 (satisfy_campaign), INDEX IDX_E21BFFF2336C40B7 (satisfy_customer), PRIMARY KEY(satisfy_campaign, satisfy_customer))");
		$this->addSql("ALTER TABLE famelo_satisfy_domain_model_campaign_customers_join ADD CONSTRAINT FK_E21BFFF2AD40DC63 FOREIGN KEY (satisfy_campaign) REFERENCES famelo_satisfy_domain_model_campaign (persistence_object_identifier)");
		$this->addSql("ALTER TABLE famelo_satisfy_domain_model_campaign_customers_join ADD CONSTRAINT FK_E21BFFF2336C40B7 FOREIGN KEY (satisfy_customer) REFERENCES famelo_satisfy_domain_model_customer (persistence_object_identifier)");
		$this->addSql("DROP TABLE famelo_satisfy_domain_model_campaign_customer_join");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("CREATE TABLE famelo_satisfy_domain_model_campaign_customer_join (satisfy_campaign VARCHAR(40) NOT NULL, satisfy_customer VARCHAR(40) NOT NULL, INDEX IDX_A1DEACD9AD40DC63 (satisfy_campaign), INDEX IDX_A1DEACD9336C40B7 (satisfy_customer), PRIMARY KEY(satisfy_campaign, satisfy_customer))");
		$this->addSql("ALTER TABLE famelo_satisfy_domain_model_campaign_customer_join ADD CONSTRAINT FK_A1DEACD9336C40B7 FOREIGN KEY (satisfy_customer) REFERENCES famelo_satisfy_domain_model_customer (persistence_object_identifier)");
		$this->addSql("ALTER TABLE famelo_satisfy_domain_model_campaign_customer_join ADD CONSTRAINT FK_A1DEACD9AD40DC63 FOREIGN KEY (satisfy_campaign) REFERENCES famelo_satisfy_domain_model_campaign (persistence_object_identifier)");
	}
}

?>