<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121103211555 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE famelo_adu_domain_model_answer (persistence_object_identifier VARCHAR(40) NOT NULL, question VARCHAR(40) DEFAULT NULL, answer VARCHAR(255) NOT NULL, comment VARCHAR(255) NOT NULL, INDEX IDX_A0955BF3B6F7494E (question), PRIMARY KEY(persistence_object_identifier))");
		$this->addSql("CREATE TABLE famelo_adu_domain_model_category (persistence_object_identifier VARCHAR(40) NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(persistence_object_identifier))");
		$this->addSql("CREATE TABLE famelo_adu_domain_model_contact (persistence_object_identifier VARCHAR(40) NOT NULL, firstname VARCHAR(255) NOT NULL, lastname VARCHAR(255) NOT NULL, phone VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, PRIMARY KEY(persistence_object_identifier))");
		$this->addSql("CREATE TABLE famelo_adu_domain_model_question (persistence_object_identifier VARCHAR(40) NOT NULL, body VARCHAR(255) NOT NULL, weight INT NOT NULL, type VARCHAR(255) NOT NULL, PRIMARY KEY(persistence_object_identifier))");
		$this->addSql("CREATE TABLE famelo_adu_domain_model_branch (persistence_object_identifier VARCHAR(40) NOT NULL, name VARCHAR(255) NOT NULL, branch VARCHAR(255) NOT NULL, questions LONGTEXT NOT NULL COMMENT '(DC2Type:array)', PRIMARY KEY(persistence_object_identifier))");
		$this->addSql("CREATE TABLE famelo_adu_domain_model_user (persistence_object_identifier VARCHAR(40) NOT NULL, branch VARCHAR(40) DEFAULT NULL, firstname VARCHAR(255) NOT NULL, lastname VARCHAR(255) NOT NULL, phone VARCHAR(255) NOT NULL, mobile VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, role VARCHAR(255) NOT NULL, INDEX IDX_C4FBE4FFBB861B1F (branch), PRIMARY KEY(persistence_object_identifier))");
		$this->addSql("CREATE TABLE famelo_adu_domain_model_customer (persistence_object_identifier VARCHAR(40) NOT NULL, contact VARCHAR(40) DEFAULT NULL, alternativecontact VARCHAR(40) DEFAULT NULL, category VARCHAR(40) DEFAULT NULL, consultant VARCHAR(40) DEFAULT NULL, branch VARCHAR(40) DEFAULT NULL, name VARCHAR(255) NOT NULL, cycle INT NOT NULL, INDEX IDX_3CEBB62A4C62E638 (contact), INDEX IDX_3CEBB62A16C72839 (alternativecontact), INDEX IDX_3CEBB62A64C19C1 (category), INDEX IDX_3CEBB62A441282A1 (consultant), INDEX IDX_3CEBB62ABB861B1F (branch), PRIMARY KEY(persistence_object_identifier))");
		$this->addSql("ALTER TABLE famelo_adu_domain_model_answer ADD CONSTRAINT FK_A0955BF3B6F7494E FOREIGN KEY (question) REFERENCES famelo_adu_domain_model_question (persistence_object_identifier)");
		$this->addSql("ALTER TABLE famelo_adu_domain_model_user ADD CONSTRAINT FK_C4FBE4FFBB861B1F FOREIGN KEY (branch) REFERENCES famelo_adu_domain_model_branch (persistence_object_identifier)");
		$this->addSql("ALTER TABLE famelo_adu_domain_model_user ADD CONSTRAINT FK_C4FBE4FF47A46B0A FOREIGN KEY (persistence_object_identifier) REFERENCES typo3_party_domain_model_abstractparty (persistence_object_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE famelo_adu_domain_model_customer ADD CONSTRAINT FK_3CEBB62A4C62E638 FOREIGN KEY (contact) REFERENCES famelo_adu_domain_model_contact (persistence_object_identifier)");
		$this->addSql("ALTER TABLE famelo_adu_domain_model_customer ADD CONSTRAINT FK_3CEBB62A16C72839 FOREIGN KEY (alternativecontact) REFERENCES famelo_adu_domain_model_contact (persistence_object_identifier)");
		$this->addSql("ALTER TABLE famelo_adu_domain_model_customer ADD CONSTRAINT FK_3CEBB62A64C19C1 FOREIGN KEY (category) REFERENCES famelo_adu_domain_model_category (persistence_object_identifier)");
		$this->addSql("ALTER TABLE famelo_adu_domain_model_customer ADD CONSTRAINT FK_3CEBB62A441282A1 FOREIGN KEY (consultant) REFERENCES famelo_adu_domain_model_user (persistence_object_identifier)");
		$this->addSql("ALTER TABLE famelo_adu_domain_model_customer ADD CONSTRAINT FK_3CEBB62ABB861B1F FOREIGN KEY (branch) REFERENCES famelo_adu_domain_model_branch (persistence_object_identifier)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE famelo_adu_domain_model_customer DROP FOREIGN KEY FK_3CEBB62A64C19C1");
		$this->addSql("ALTER TABLE famelo_adu_domain_model_customer DROP FOREIGN KEY FK_3CEBB62A4C62E638");
		$this->addSql("ALTER TABLE famelo_adu_domain_model_customer DROP FOREIGN KEY FK_3CEBB62A16C72839");
		$this->addSql("ALTER TABLE famelo_adu_domain_model_answer DROP FOREIGN KEY FK_A0955BF3B6F7494E");
		$this->addSql("ALTER TABLE famelo_adu_domain_model_user DROP FOREIGN KEY FK_C4FBE4FFBB861B1F");
		$this->addSql("ALTER TABLE famelo_adu_domain_model_customer DROP FOREIGN KEY FK_3CEBB62ABB861B1F");
		$this->addSql("ALTER TABLE famelo_adu_domain_model_customer DROP FOREIGN KEY FK_3CEBB62A441282A1");
		$this->addSql("DROP TABLE famelo_adu_domain_model_answer");
		$this->addSql("DROP TABLE famelo_adu_domain_model_category");
		$this->addSql("DROP TABLE famelo_adu_domain_model_contact");
		$this->addSql("DROP TABLE famelo_adu_domain_model_question");
		$this->addSql("DROP TABLE famelo_adu_domain_model_branch");
		$this->addSql("DROP TABLE famelo_adu_domain_model_user");
		$this->addSql("DROP TABLE famelo_adu_domain_model_customer");
	}
}

?>