<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140930113253 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE famelo_satisfy_domain_model_mailsurvey DROP FOREIGN KEY FK_BA07A2614C62E638");
		$this->addSql("ALTER TABLE famelo_satisfy_domain_model_mailsurvey ADD CONSTRAINT FK_BA07A2614C62E638 FOREIGN KEY (contact) REFERENCES famelo_satisfy_domain_model_contact (persistence_object_identifier) ON DELETE CASCADE");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE famelo_satisfy_domain_model_mailsurvey DROP FOREIGN KEY FK_BA07A2614C62E638");
		$this->addSql("ALTER TABLE famelo_satisfy_domain_model_mailsurvey ADD CONSTRAINT FK_BA07A2614C62E638 FOREIGN KEY (contact) REFERENCES famelo_satisfy_domain_model_contact (persistence_object_identifier)");
	}
}

?>