<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131031185610 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("ALTER TABLE famelo_satisfy_domain_model_contact ADD customer VARCHAR(40) DEFAULT NULL");
		$this->addSql("ALTER TABLE famelo_satisfy_domain_model_contact ADD CONSTRAINT FK_440239BA81398E09 FOREIGN KEY (customer) REFERENCES famelo_satisfy_domain_model_customer (persistence_object_identifier)");
		$this->addSql("CREATE INDEX IDX_440239BA81398E09 ON famelo_satisfy_domain_model_contact (customer)");
		$this->addSql("ALTER TABLE famelo_satisfy_domain_model_customer DROP FOREIGN KEY FK_82870CDA16C72839");
		$this->addSql("DROP INDEX IDX_82870CDA16C72839 ON famelo_satisfy_domain_model_customer");
		$this->addSql("ALTER TABLE famelo_satisfy_domain_model_customer DROP alternativecontact");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("ALTER TABLE famelo_satisfy_domain_model_contact DROP FOREIGN KEY FK_440239BA81398E09");
		$this->addSql("DROP INDEX IDX_440239BA81398E09 ON famelo_satisfy_domain_model_contact");
		$this->addSql("ALTER TABLE famelo_satisfy_domain_model_contact DROP customer");
		$this->addSql("ALTER TABLE famelo_satisfy_domain_model_customer ADD alternativecontact VARCHAR(40) DEFAULT NULL");
		$this->addSql("ALTER TABLE famelo_satisfy_domain_model_customer ADD CONSTRAINT FK_82870CDA16C72839 FOREIGN KEY (alternativecontact) REFERENCES famelo_satisfy_domain_model_contact (persistence_object_identifier)");
		$this->addSql("CREATE INDEX IDX_82870CDA16C72839 ON famelo_satisfy_domain_model_customer (alternativecontact)");
	}
}

?>