<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121119223038 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE famelo_adu_domain_model_rating (persistence_object_identifier VARCHAR(40) NOT NULL, created DATETIME NOT NULL, level INT NOT NULL, comment VARCHAR(255) NOT NULL, PRIMARY KEY(persistence_object_identifier))");
		$this->addSql("CREATE TABLE famelo_adu_domain_model_survey (persistence_object_identifier VARCHAR(40) NOT NULL, customer VARCHAR(40) DEFAULT NULL, rating VARCHAR(40) DEFAULT NULL, created DATETIME NOT NULL, INDEX IDX_D7178A2A81398E09 (customer), UNIQUE INDEX UNIQ_D7178A2AD8892622 (rating), PRIMARY KEY(persistence_object_identifier))");
		$this->addSql("ALTER TABLE famelo_adu_domain_model_survey ADD CONSTRAINT FK_D7178A2A81398E09 FOREIGN KEY (customer) REFERENCES famelo_adu_domain_model_customer (persistence_object_identifier)");
		$this->addSql("ALTER TABLE famelo_adu_domain_model_survey ADD CONSTRAINT FK_D7178A2AD8892622 FOREIGN KEY (rating) REFERENCES famelo_adu_domain_model_rating (persistence_object_identifier)");
		$this->addSql("ALTER TABLE famelo_adu_domain_model_user DROP firstname, DROP lastname");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE famelo_adu_domain_model_survey DROP FOREIGN KEY FK_D7178A2AD8892622");
		$this->addSql("DROP TABLE famelo_adu_domain_model_rating");
		$this->addSql("DROP TABLE famelo_adu_domain_model_survey");
		$this->addSql("ALTER TABLE famelo_adu_domain_model_user ADD firstname VARCHAR(255) NOT NULL, ADD lastname VARCHAR(255) NOT NULL");
	}
}

?>