<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140930112741 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE famelo_satisfy_domain_model_contact DROP FOREIGN KEY FK_440239BA81398E09");
		$this->addSql("ALTER TABLE famelo_satisfy_domain_model_contact ADD CONSTRAINT FK_440239BA81398E09 FOREIGN KEY (customer) REFERENCES famelo_satisfy_domain_model_customer (persistence_object_identifier) ON DELETE CASCADE");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE famelo_satisfy_domain_model_contact DROP FOREIGN KEY FK_440239BA81398E09");
		$this->addSql("ALTER TABLE famelo_satisfy_domain_model_contact ADD CONSTRAINT FK_440239BA81398E09 FOREIGN KEY (customer) REFERENCES famelo_satisfy_domain_model_customer (persistence_object_identifier)");
	}
}

?>