<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140930120322 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE famelo_satisfy_domain_model_campaign_contacts_join DROP FOREIGN KEY FK_F52EADF7A4A77081");
		$this->addSql("ALTER TABLE famelo_satisfy_domain_model_campaign_contacts_join DROP FOREIGN KEY FK_F52EADF7AD40DC63");
		$this->addSql("ALTER TABLE famelo_satisfy_domain_model_campaign_contacts_join ADD CONSTRAINT FK_F52EADF7A4A77081 FOREIGN KEY (satisfy_contact) REFERENCES famelo_satisfy_domain_model_contact (persistence_object_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE famelo_satisfy_domain_model_campaign_contacts_join ADD CONSTRAINT FK_F52EADF7AD40DC63 FOREIGN KEY (satisfy_campaign) REFERENCES famelo_satisfy_domain_model_campaign (persistence_object_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE famelo_satisfy_domain_model_result DROP FOREIGN KEY FK_1E886E5E13A4D50F");
		$this->addSql("ALTER TABLE famelo_satisfy_domain_model_result ADD CONSTRAINT FK_1E886E5E13A4D50F FOREIGN KEY (mailsurvey) REFERENCES famelo_satisfy_domain_model_mailsurvey (persistence_object_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE famelo_satisfy_domain_model_mailsurvey DROP FOREIGN KEY FK_BA07A2614C62E638");
		$this->addSql("ALTER TABLE famelo_satisfy_domain_model_mailsurvey DROP FOREIGN KEY FK_BA07A2611F1512DD");
		$this->addSql("ALTER TABLE famelo_satisfy_domain_model_mailsurvey ADD CONSTRAINT FK_BA07A2614C62E638 FOREIGN KEY (contact) REFERENCES famelo_satisfy_domain_model_contact (persistence_object_identifier) ON DELETE SET NULL");
		$this->addSql("ALTER TABLE famelo_satisfy_domain_model_mailsurvey ADD CONSTRAINT FK_BA07A2611F1512DD FOREIGN KEY (campaign) REFERENCES famelo_satisfy_domain_model_campaign (persistence_object_identifier) ON DELETE SET NULL");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE famelo_satisfy_domain_model_campaign_contacts_join DROP FOREIGN KEY FK_F52EADF7AD40DC63");
		$this->addSql("ALTER TABLE famelo_satisfy_domain_model_campaign_contacts_join DROP FOREIGN KEY FK_F52EADF7A4A77081");
		$this->addSql("ALTER TABLE famelo_satisfy_domain_model_campaign_contacts_join ADD CONSTRAINT FK_F52EADF7AD40DC63 FOREIGN KEY (satisfy_campaign) REFERENCES famelo_satisfy_domain_model_campaign (persistence_object_identifier)");
		$this->addSql("ALTER TABLE famelo_satisfy_domain_model_campaign_contacts_join ADD CONSTRAINT FK_F52EADF7A4A77081 FOREIGN KEY (satisfy_contact) REFERENCES famelo_satisfy_domain_model_contact (persistence_object_identifier)");
		$this->addSql("ALTER TABLE famelo_satisfy_domain_model_mailsurvey DROP FOREIGN KEY FK_BA07A2614C62E638");
		$this->addSql("ALTER TABLE famelo_satisfy_domain_model_mailsurvey DROP FOREIGN KEY FK_BA07A2611F1512DD");
		$this->addSql("ALTER TABLE famelo_satisfy_domain_model_mailsurvey ADD CONSTRAINT FK_BA07A2614C62E638 FOREIGN KEY (contact) REFERENCES famelo_satisfy_domain_model_contact (persistence_object_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE famelo_satisfy_domain_model_mailsurvey ADD CONSTRAINT FK_BA07A2611F1512DD FOREIGN KEY (campaign) REFERENCES famelo_satisfy_domain_model_campaign (persistence_object_identifier)");
		$this->addSql("ALTER TABLE famelo_satisfy_domain_model_result DROP FOREIGN KEY FK_1E886E5E13A4D50F");
		$this->addSql("ALTER TABLE famelo_satisfy_domain_model_result ADD CONSTRAINT FK_1E886E5E13A4D50F FOREIGN KEY (mailsurvey) REFERENCES famelo_satisfy_domain_model_mailsurvey (persistence_object_identifier)");
	}
}

?>