<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131103001836 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("CREATE TABLE famelo_satisfy_domain_model_campaign (persistence_object_identifier VARCHAR(40) NOT NULL, name VARCHAR(255) NOT NULL, start DATETIME DEFAULT NULL, PRIMARY KEY(persistence_object_identifier))");
		$this->addSql("CREATE TABLE famelo_satisfy_domain_model_campaign_questions_join (satisfy_campaign VARCHAR(40) NOT NULL, satisfy_question VARCHAR(40) NOT NULL, INDEX IDX_1CC59BCDAD40DC63 (satisfy_campaign), INDEX IDX_1CC59BCD4A287F0 (satisfy_question), PRIMARY KEY(satisfy_campaign, satisfy_question))");
		$this->addSql("ALTER TABLE famelo_satisfy_domain_model_campaign_questions_join ADD CONSTRAINT FK_1CC59BCDAD40DC63 FOREIGN KEY (satisfy_campaign) REFERENCES famelo_satisfy_domain_model_campaign (persistence_object_identifier)");
		$this->addSql("ALTER TABLE famelo_satisfy_domain_model_campaign_questions_join ADD CONSTRAINT FK_1CC59BCD4A287F0 FOREIGN KEY (satisfy_question) REFERENCES famelo_satisfy_domain_model_question (persistence_object_identifier)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("ALTER TABLE famelo_satisfy_domain_model_campaign_questions_join DROP FOREIGN KEY FK_1CC59BCDAD40DC63");
		$this->addSql("DROP TABLE famelo_satisfy_domain_model_campaign");
		$this->addSql("DROP TABLE famelo_satisfy_domain_model_campaign_questions_join");
	}
}

?>