<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131104113511 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("CREATE TABLE famelo_satisfy_domain_model_result (persistence_object_identifier VARCHAR(40) NOT NULL, mailsurvey VARCHAR(40) DEFAULT NULL, question VARCHAR(255) NOT NULL, date DATETIME NOT NULL, data VARCHAR(255) NOT NULL, INDEX IDX_1E886E5E13A4D50F (mailsurvey), PRIMARY KEY(persistence_object_identifier))");
		$this->addSql("CREATE TABLE famelo_satisfy_domain_model_mailsurvey (persistence_object_identifier VARCHAR(40) NOT NULL, contact VARCHAR(40) DEFAULT NULL, campaign VARCHAR(40) DEFAULT NULL, created DATETIME NOT NULL, INDEX IDX_BA07A2614C62E638 (contact), INDEX IDX_BA07A2611F1512DD (campaign), PRIMARY KEY(persistence_object_identifier))");
		$this->addSql("ALTER TABLE famelo_satisfy_domain_model_result ADD CONSTRAINT FK_1E886E5E13A4D50F FOREIGN KEY (mailsurvey) REFERENCES famelo_satisfy_domain_model_mailsurvey (persistence_object_identifier)");
		$this->addSql("ALTER TABLE famelo_satisfy_domain_model_mailsurvey ADD CONSTRAINT FK_BA07A2614C62E638 FOREIGN KEY (contact) REFERENCES famelo_satisfy_domain_model_contact (persistence_object_identifier)");
		$this->addSql("ALTER TABLE famelo_satisfy_domain_model_mailsurvey ADD CONSTRAINT FK_BA07A2611F1512DD FOREIGN KEY (campaign) REFERENCES famelo_satisfy_domain_model_campaign (persistence_object_identifier)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("ALTER TABLE famelo_satisfy_domain_model_result DROP FOREIGN KEY FK_1E886E5E13A4D50F");
		$this->addSql("DROP TABLE famelo_satisfy_domain_model_result");
		$this->addSql("DROP TABLE famelo_satisfy_domain_model_mailsurvey");
	}
}

?>