<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131122113106 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE famelo_satisfy_domain_model_campaign_questions_join DROP FOREIGN KEY FK_1CC59BCD4A287F0");
		$this->addSql("ALTER TABLE famelo_satisfy_domain_model_campaign_questions_join ADD CONSTRAINT FK_1CC59BCD4A287F0 FOREIGN KEY (satisfy_question) REFERENCES famelo_satisfy_domain_model_question (persistence_object_identifier) ON DELETE CASCADE");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE famelo_satisfy_domain_model_campaign_questions_join DROP FOREIGN KEY FK_1CC59BCD4A287F0");
		$this->addSql("ALTER TABLE famelo_satisfy_domain_model_campaign_questions_join ADD CONSTRAINT FK_1CC59BCD4A287F0 FOREIGN KEY (satisfy_question) REFERENCES famelo_satisfy_domain_model_question (persistence_object_identifier)");
	}
}

?>