<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130123130228 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE famelo_adu_domain_model_survey_answers_join (adu_survey VARCHAR(40) NOT NULL, adu_answer VARCHAR(40) NOT NULL, INDEX IDX_FD9A0951F190EB65 (adu_survey), INDEX IDX_FD9A095186123ABC (adu_answer), PRIMARY KEY(adu_survey, adu_answer))");
		$this->addSql("ALTER TABLE famelo_adu_domain_model_survey_answers_join ADD CONSTRAINT FK_FD9A0951F190EB65 FOREIGN KEY (adu_survey) REFERENCES famelo_adu_domain_model_survey (persistence_object_identifier)");
		$this->addSql("ALTER TABLE famelo_adu_domain_model_survey_answers_join ADD CONSTRAINT FK_FD9A095186123ABC FOREIGN KEY (adu_answer) REFERENCES famelo_adu_domain_model_answer (persistence_object_identifier)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("DROP TABLE famelo_adu_domain_model_survey_answers_join");
	}
}

?>