TYPO3:
  Flow:
    security:
      authentication:
        providers:
          SatisfyProvider:
            provider: PersistedUsernamePasswordProvider
            entryPoint: 'WebRedirect'
            entryPointOptions:
              uri: login
    object:
      excludeClasses:
       'Famelo.Faces' : ['.*']
       'fzaninotto.faker' : ['.*']
       'Behat.Gherkin' : ['.*']
       'guzzle.guzzle' : ['.*']
       'symfony.config' : ['.*']
       'symfony.dependencyinjection' : ['.*']
       'symfony.browserkit' : ['.*']
       'symfony.cssselector' : ['.*']
       'symfony.eventdispatcher' : ['.*']
       'symfony.finder' : ['.*']
       'symfony.process' : ['.*']
       'symfony.translation' : ['.*']
       'behat.minkbrowserkitdriver': ['.*']
       'behat.minkzombiedriver': ['.*']
       'behat.minkselenium2driver': ['.*']
       'fabpot.goutte': ['.*']
       'famelo.behat' : ['.*']
       'famelo.minkextension' : ['.*']
       'famelo.minkgouttedriver': ['.*']
       'famelo.poltergeist': ['.*']
       'gChartPhp.gChartPhp': ['.*']

    i18n:
      # The default locale identifier.
      defaultLocale: de

  # Form:
  #   presets:
  #     expose:
  #       javaScripts:
  #         raty:
  #           source: 'resource://Famelo.Satisfy/Public/components/raty/js/jquery.raty.min.js'

  SwiftMailer:
    transport:
      type: 'Swift_SmtpTransport'
      options:
        host: 'mail.Satisfy-kundenzufriedenheit.com'
        port: '465'
        username: 'p182917p1'
        password: 'larivai97'
        encryption: 'ssl'
Famelo:
  Kundenbefragung:
    E-Mails:
      MoreInformation:
        - mneuhaus@famelo.com

  Impersonate:
    Role: Famelo.Satisfy:Administrator