Famelo:
  Satisfy:
    Email:
      "mneuhaus@famelo.com": Famelo.Satisfy

  Kundenbefragung:
    E-Mails:
      MoreInformation:
        - mneuhaus@famelo.com

  Impersonate:
    Role: Famelo.Satisfy:Administrator

TYPO3:
  SwiftMailer:
    transport:
      type: 'Swift_SmtpTransport'
      options:
        host: 'mail51.mittwald.de'
        username: 'p208340p1'
        password: 'comatio78'
  Flow:
    security:
      authentication:
        providers:
          SatisfyProvider:
            provider: PersistedUsernamePasswordProvider
            entryPoint: 'WebRedirect'
            entryPointOptions:
              uri: login
    i18n:
      # The default locale identifier.
      defaultLocale: de

    object:
      excludeClasses:
       'Famelo.Faces' : ['.*']
       'fzaninotto.faker' : ['.*']
       'Behat.Gherkin' : ['.*']
       'guzzle.guzzle' : ['.*']
       'symfony.config' : ['.*']
       'symfony.dependencyinjection' : ['.*']
       'symfony.browserkit' : ['.*']
       'symfony.cssselector' : ['.*']
       'symfony.eventdispatcher' : ['.*']
       'symfony.finder' : ['.*']
       'symfony.process' : ['.*']
       'symfony.translation' : ['.*']
       'davidbadura.fixtures' : ['.*']
       'DavidBadura.Fixtures' : ['.*']
       'behat.minkbrowserkitdriver': ['.*']
       'behat.minkzombiedriver': ['.*']
       'behat.minkselenium2driver': ['.*']
       'fabpot.goutte': ['.*']
       'famelo.behat' : ['.*']
       'famelo.minkextension' : ['.*']
       'famelo.minkgouttedriver': ['.*']
       'famelo.poltergeist': ['.*']
       'gChartPhp.gChartPhp': ['.*']