TYPO3:
  Flow:
    security:
      authentication:
        providers:
          ADUProvider:
            provider: PersistedUsernamePasswordProvider
            entryPoint: 'WebRedirect'
            entryPointOptions:
              uri: login
    object:
      excludeClasses:
       'Famelo.Faces' : ['.*']

    i18n:
      # The default locale identifier.
      defaultLocale: de

  Form:
    presets:
      expose:
        renderingOptions:
          submitButtonLabel: 'foobar'
#        stylesheets:
#          raty:
#            source: 'resource://SomePackage/Public/Css/File1.css'
        javaScripts:
          raty:
            source: 'resource://Famelo.ADU/Public/components/raty/js/jquery.raty.min.js'

        formElementTypes:

          'Famelo.ADU:Rating':
            superTypes: ['TYPO3.Form:SingleLineText']

          'Famelo.ADU:SingleLineTextFull':
            superTypes: ['TYPO3.Form:SingleLineText']

          'Famelo.ADU:Comment':
            superTypes: ['TYPO3.Form:SingleLineText']

          'Famelo.ADU:HiddenCustomer':
            superTypes: ['TYPO3.Expose:Hidden']

          'Famelo.ADU:HiddenQuestion':
            superTypes: ['TYPO3.Expose:Hidden']

          'Famelo.ADU:Answers':
            superTypes: ['TYPO3.Expose:InlineStacked']

          'Famelo.ADU:AnswersItem':
            superTypes: ['TYPO3.Expose:InlineStacked']