Famelo:
  ADU:
    modules:
      intro:
        label: 'Übersicht'
        arguments:
          @controller: 'Overview'
          @package: 'Famelo.ADU'

      surveys:
        label: 'Befragungen'
        arguments:
          @controller: 'Survey'
          @package: 'Famelo.ADU'

      branches:
        label: 'Niederlassungen'
        arguments:
          @controller: 'Expose'
          --exposeRuntime:
              @controller: "SameTypeList"
              @action: 'index'
              @package: "TYPO3.Expose"
              type: 'Famelo\ADU\Domain\Model\Branch'

      customers:
        label: 'Kundenmanagement'
        arguments:
          @controller: 'Expose'
          --exposeRuntime:
              @controller: "SameTypeList"
              @action: 'index'
              @package: "TYPO3.Expose"
              type: 'Famelo\ADU\Domain\Model\Customer'

      categories:
        label: 'Kategorien'
        arguments:
          @controller: 'Expose'
          --exposeRuntime:
              @controller: "SameTypeList"
              @action: 'index'
              @package: "TYPO3.Expose"
              type: 'Famelo\ADU\Domain\Model\Category'

      users:
        label: 'Nutzermanagement'
        arguments:
          @controller: 'Expose'
          --exposeRuntime:
              @controller: "SameTypeList"
              @action: 'index'
              @package: "TYPO3.Expose"
              type: 'Famelo\ADU\Domain\Model\User'

TYPO3:
  Flow:
    security:
      authentication:
        providers:
          ADUProvider:
            provider: PersistedUsernamePasswordProvider
            entryPoint: 'WebRedirect'
            entryPointOptions:
              uri: famelo.adu/login

  Form:
    presets:
      expose:
        formElementTypes:

          'Famelo.ADU:HiddenQuestion':
            superTypes: ['TYPO3.Expose:Hidden']

          'Famelo.ADU:Answers':
            superTypes: ['TYPO3.Expose:InlineStacked']

          'Famelo.ADU:AnswersItem':
            superTypes: ['TYPO3.Expose:InlineStacked']